api_msg:
  port: 5000

var_list:
  - event_time
  - ipm_dg2__sum
  - ipm_dg2__peaks
  - sc2slit_s
  - lightStatus__laser
  - lightStatus__xray

damage_list:
  - ipm2
  - ipm5
  - evr0
  - tt
  - enc

det_map:
  name: 'jungfrau4M'
  shape:
    - 2203
    - 2299
  dtype: float32
  bins: 50
